- README.md
- packages/hardhat/.env.example
- packages/hardhat/hardhat.config.ts
- packages/hardhat/package.json
- yarn.lock
> feat(hardhat): verify contracts on etherscan

- packages/hardhat/deploy/07_Setup_Contrats.ts
- packages/hardhat/hardhat.config.ts
- packages/hardhat/helper-hardhat-config.ts
- packages/hardhat/tasks/withdraw-link.ts
- packages/hardhat/test/unit/APIConsumer.test.ts
- packages/hardhat/utils.ts
> feat: withdraw link from testnet contracts

- packages/hardhat/test/unit/RandomNumberConsumer.test.ts
> test: randomness contract unit tests

- packages/hardhat/test/integration/RandomNumberConsumer.test.ts
> test: randomness contract integration test

- packages/hardhat/test/unit/PriceConsumer.test.ts
- packages/hardhat/test/unit/PriceConsumerV3.test.ts
> test: price consumer contract unit tests

- .github/workflows/main.yml
Add Github Actions workflow to:
- compile contracts
- run contracts unit tests
closes #50
> Add GH actions

- packages/hardhat/test/integration/PriceConsumer.test.ts
- packages/hardhat/test/unit/PriceConsumer.test.ts
> test: price consumer contract integration test

- packages/hardhat/test/integration/APIConsumer.test.ts
- packages/hardhat/test/integration/RandomNumberConsumer.test.ts
- packages/hardhat/test/unit/APIConsumer.test.ts
- packages/hardhat/test/unit/RandomNumberConsumer.test.ts
- packages/hardhat/test/unit/RandomSVG.test.ts
> fix: types in tests

- .github/workflows/main.yml
- README.md
- package.json
- packages/hardhat/hardhat.config.ts
- packages/hardhat/package.json
> Integrate coveralls.io

- packages/hardhat/deploy/00_Deploy_Multicall.ts
- packages/hardhat/deploy/01_Deploy_Mocks.ts
- packages/hardhat/deploy/02_Deploy_PriceConsumer.ts
- packages/hardhat/deploy/03_Deploy_PriceConsumerV3.ts
- packages/hardhat/deploy/04_Deploy_RandomNumberConsumer.ts
- packages/hardhat/deploy/05_Deploy_RandomSVG.ts
- packages/hardhat/deploy/06_Deploy_APIConsumer.ts
- packages/hardhat/package.json
> feat: deploy contracts without auto-funding

- packages/frontend/components/vrf/RandomNFT/ExternalLink.tsx
- packages/frontend/components/vrf/RandomNFT/index.tsx
- packages/frontend/package.json
- yarn.lock
> feat(frontend): external link to generated nft

- packages/frontend/components/ConnectWallet.tsx
- packages/frontend/components/Error.tsx
- packages/frontend/components/feeds/SelectFeed.tsx
- packages/frontend/components/layout/Layout.tsx
- packages/frontend/components/vrf/RandomNFT/index.tsx
- packages/frontend/components/vrf/RandomNumber.tsx
- packages/frontend/lib/utils.ts
- packages/frontend/pages/external-api.tsx
> Show available networks

- README.md
- package.json
> Finish readme

- packages/frontend/components/api/Consumer.tsx
- packages/frontend/components/layout/Layout.tsx
- packages/frontend/pages/external-api.tsx
- packages/frontend/pages/feeds.tsx
- packages/frontend/pages/vrf.tsx
> Feature descriptions and links

- packages/frontend/components/vrf/RandomNFT/index.tsx
> chore(frontend): add tooltips to nft buttons

- packages/frontend/components/api/RequestBuilder.tsx
- packages/frontend/components/api/index.ts
- packages/frontend/conf/config.ts
- packages/frontend/pages/external-api.tsx
> feat: any api request builder integer frontend

- packages/frontend/pages/external-api.tsx
- packages/frontend/pages/index.tsx
> feat(frontend): home page

- packages/frontend/components/api/RequestBuilder.tsx
- packages/frontend/components/vrf/RandomNFT/index.tsx
- packages/frontend/components/vrf/RandomNumber.tsx
Disabled all buttons when no metamask connected
closes #79
> feat: disable all buttons when no metamask connected

- packages/frontend/components/vrf/RandomNFT/index.tsx
- packages/frontend/components/vrf/RandomNumber.tsx
> fix(frontend): disable buttons while loading

- packages/frontend/components/api/RequestBuilder.tsx
> fix(frontend): input color on grey bg

- packages/frontend/components/api/RequestBuilder.tsx
- packages/frontend/components/vrf/RandomNFT/index.tsx
- packages/frontend/components/vrf/RandomNumber.tsx
- packages/frontend/lib/utils.ts
> feat: detect when contract needs link

- README.md
Add requirements to test the frontend, namely wallet and test $link $eth.
> Add frontend prereqs
